# -*- coding: utf-8 -*-
"""Copia de Clasificación de imágenes con Python y Tensorflow - Redes Densas

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/190gblp8x0wVmoWV97EVsF0OfdezV1XcX
"""

import os
# Fuerza a TensorFlow a utilizar el formato legado de Keras 2
os.environ["TF_USE_LEGACY_KERAS"] = "1"

import tensorflow as tf
import tensorflow_datasets as tfds

#Descargar set de datos de Fashion MNIST de Zalando
(datos_entrenamiento, etiquetas_entreno), (datos_pruebas, etiquetas_prueba) = tf.keras.datasets.fashion_mnist.load_data()

#Imprimir los metadatos para ver que trae el set
datos_entrenamiento

#Etiquetas de las 10 categorias posibles
nombres_clases = ['Camiseta', 'Pantalón', 'Suéter', 'Vestido', 'Abrigo',
                  'Sandalia', 'Camisa', 'Zapatilla', 'Bolso', 'Botín']

nombres_clases

import tensorflow as tf

# Funcion de preprocesamiento para los datos: normalizar y añadir dimension de canal
def preprocesar(imagenes, etiquetas):
  # Asegurarse de que las imagenes esten en float32 y normalizadas a [0, 1]
  imagenes = tf.cast(imagenes, tf.float32) # Cast to float32
  imagenes = imagenes / 255.0 # Normalize to 0-1 (this is the ONLY normalization step)
  imagenes = tf.expand_dims(imagenes, axis=-1) # Add channel dimension (28, 28) -> (28, 28, 1)
  etiquetas = tf.cast(etiquetas, tf.int64) # Cast labels to tf.int64 for SparseCategoricalCrossentropy
  return imagenes, etiquetas

# Convertir los arreglos de NumPy a objetos Dataset de TensorFlow
dataset_entreno = tf.data.Dataset.from_tensor_slices((datos_entrenamiento, etiquetas_entreno))
dataset_prueba = tf.data.Dataset.from_tensor_slices((datos_pruebas, etiquetas_prueba))

# Aplicar la funcion de preprocesamiento a los datasets
dataset_entreno = dataset_entreno.map(preprocesar, num_parallel_calls=tf.data.AUTOTUNE)
dataset_prueba = dataset_prueba.map(preprocesar, num_parallel_calls=tf.data.AUTOTUNE)

# Aplicar Caché, Shuffle (mezclar) y Batch (lotes) para optimizar el entrenamiento
TAMANO_LOTE = 32

dataset_entreno = dataset_entreno.cache().shuffle(60000).batch(TAMANO_LOTE).prefetch(tf.data.AUTOTUNE)
dataset_prueba = dataset_prueba.cache().batch(TAMANO_LOTE).prefetch(tf.data.AUTOTUNE)

#Mostrar una imagen de los datos de pruebas, de momento mostremos la primera
for imagenes, etiqueta in dataset_entreno.take(1):
  break
imagen = imagenes[0].numpy().reshape((28,28)) #Redimensionar, cosas de tensores, lo veremos despues

import matplotlib.pyplot as plt

#Dibujar dibujar
plt.figure()
plt.imshow(imagen, cmap=plt.cm.binary)
plt.colorbar()
plt.grid(False)
plt.show()

#Crear el modelo
modelo = tf.keras.Sequential([
  tf.keras.Input(shape=(28, 28, 1)), # Capa de entrada explícita
  tf.keras.layers.Flatten(),
  tf.keras.layers.Dense(50, activation=tf.nn.relu),
  tf.keras.layers.Dense(50, activation=tf.nn.relu),
  tf.keras.layers.Dense(10, activation=tf.nn.softmax) #Para redes de clasificacion
])

#Compilar el modelo
modelo.compile(
    optimizer='adam',
    loss=tf.keras.losses.SparseCategoricalCrossentropy(),
    metrics=['accuracy']
)

#Los numeros de datos en entrenamiento y pruebas (60k y 10k)
num_ej_entrenamiento = datos_entrenamiento.shape[0]
num_ej_pruebas = datos_pruebas.shape[0]

#Shuffle y repeat hacen que los datos esten mezclados de manera aleatoria para que la red
#no se vaya a aprender el orden de las cosas
dataset_entreno = dataset_entreno.repeat().shuffle(num_ej_entrenamiento).batch(TAMANO_LOTE)
dataset_prueba = dataset_prueba.batch(TAMANO_LOTE)

import math
historial = modelo.fit(
    dataset_entreno,
    epochs=5,
    steps_per_epoch=math.ceil(num_ej_entrenamiento / TAMANO_LOTE)
)

#Ver la funcion de perdida
plt.xlabel("# Epoca")
plt.ylabel("Magnitud de pérdida")
plt.plot(historial.history["loss"])

#Pintar una cuadricula con varias predicciones, y marcar si fue correcta (azul) o incorrecta (roja)
import numpy as np

for imagenes_prueba, etiquetas_prueba in dataset_prueba.take(1):
  imagenes_prueba = imagenes_prueba.numpy()
  etiquetas_prueba = etiquetas_prueba.numpy()
  predicciones = modelo.predict(imagenes_prueba)

def graficar_imagen(i, arr_predicciones, etiquetas_reales, imagenes):
  arr_predicciones, etiqueta_real, img = arr_predicciones[i], etiquetas_reales[i], imagenes[i]
  plt.grid(False)
  plt.xticks([])
  plt.yticks([])

  plt.imshow(img[...,0], cmap=plt.cm.binary)

  etiqueta_prediccion = np.argmax(arr_predicciones)
  if etiqueta_prediccion == etiqueta_real:
    color = 'blue'
  else:
    color = 'red'

  plt.xlabel("{} {:2.0f}% ({})".format(nombres_clases[etiqueta_prediccion],
                                100*np.max(arr_predicciones),
                                nombres_clases[etiqueta_real]),
                                color=color)

def graficar_valor_arreglo(i, arr_predicciones, etiqueta_real):
  arr_predicciones, etiqueta_real = arr_predicciones[i], etiqueta_real[i]
  plt.grid(False)
  plt.xticks([])
  plt.yticks([])
  grafica = plt.bar(range(10), arr_predicciones, color="#777777")
  plt.ylim([0, 1])
  etiqueta_prediccion = np.argmax(arr_predicciones)

  grafica[etiqueta_prediccion].set_color('red')
  grafica[etiqueta_real].set_color('blue')

filas = 5
columnas = 5
num_imagenes = filas*columnas
plt.figure(figsize=(2*2*columnas, 2*filas))
for i in range(num_imagenes):
  plt.subplot(filas, 2*columnas, 2*i+1)
  graficar_imagen(i, predicciones, etiquetas_prueba, imagenes_prueba)
  plt.subplot(filas, 2*columnas, 2*i+2)
  graficar_valor_arreglo(i, predicciones, etiquetas_prueba)

#Probar una imagen suelta
imagen = imagenes_prueba[8]
imagen = np.array([imagen])
prediccion = modelo.predict(imagen)

print("Prediccion: " + nombres_clases[np.argmax(prediccion[0])])

#Exportacion del modelo a h5
modelo.save('modelo_exportado.h5')

#Instalar tensorflowjs para convertir el h5 a un modelo que pueda cargar tensorflowjs en un explorador
!pip install tensorflowjs

#Convertir el archivo h5 a formato de tensorflowjs
!mkdir tfjs_target_dir
!tensorflowjs_converter --input_format keras modelo_exportado.h5 tfjs_target_dir

#Veamos si si creo la carpeta
!ls

#Veamos el contenido de la carpeta
!ls tfjs_target_dir

# 1. Montar Google Drive
from google.colab import drive
drive.mount('/content/drive')

# 2. Definir la ruta de destino en Google Drive y crear la carpeta si no existe
drive_path = '/content/drive/MyDrive/tfjs_model_2'
!mkdir -p "{drive_path}"

# 3. Copiar los archivos del modelo a Google Drive
!cp -r tfjs_target_dir/* "{drive_path}"

print(f"Archivos copiados a: {drive_path}")
!ls "{drive_path}"